MERGE INTO {{DATABASE}}.{{SCHEMA}}.{{TABLE1}} AS b USING (
    SELECT 
            ID_H_EP ,
            NAME_H_EP ,
            DATETIME_H_EP ,
            DEPARTMENT_ID ,
            JOB_ID 
    FROM {{DATABASE}}.{{SCHEMA2}}.{{TABLE1}}_RAW

) AS a on
    a.ID_H_EP = b.ID_H_EP
    AND a.NAME_H_EP = b.NAME_H_EP
    AND a.DATETIME_H_EP = b.DATETIME_H_EP
    AND a.DEPARTMENT_ID = b.DEPARTMENT_ID
    AND a.JOB_ID = b.JOB_ID
WHEN NOT MATCHED THEN INSERT (ID_H_EP, NAME_H_EP, DATETIME_H_EP,DEPARTMENT_ID,JOB_ID ) 
VALUES (a.ID_H_EP, a.NAME_H_EP, a.DATETIME_H_EP,a.DEPARTMENT_ID,a.JOB_ID);


MERGE INTO {{DATABASE}}.{{SCHEMA}}.{{TABLE2}} AS b USING (
    SELECT 
        ID_D ,
        DEPARTMENT_NAME 
    FROM {{DATABASE}}.{{SCHEMA2}}.{{TABLE2}}_RAW

) AS a on
        a.ID_D =  b.ID_D 
        AND a.DEPARTMENT_NAME = b.DEPARTMENT_NAME
WHEN NOT MATCHED THEN INSERT (ID_D ,DEPARTMENT_NAME) 
VALUES ( a.ID_D ,a.DEPARTMENT_NAME );


MERGE INTO {{DATABASE}}.{{ SCHEMA}}.{{TABLE3}} AS b USING (
    SELECT 
        ID_J ,
        JOB_NAME 
    FROM {{DATABASE}}.{{SCHEMA2}}.{{TABLE3}}_RAW

) AS a on
        a.ID_J =  b.ID_J 
        AND a.JOB_NAME = b.JOB_NAME
WHEN NOT MATCHED THEN INSERT (ID_J ,JOB_NAME) 
VALUES ( a.ID_J ,a.JOB_NAME );


TRUNCATE TABLE IF EXISTS {{DATABASE}}.{{SCHEMA2}}.{{TABLE1}}_RAW;

TRUNCATE TABLE IF EXISTS {{DATABASE}}.{{SCHEMA2}}.{{TABLE2}}_RAW;

TRUNCATE TABLE IF EXISTS {{DATABASE}}.{{SCHEMA2}}.{{TABLE3}}_RAW;