USE ROLE ACCOUNTADMIN;
CREATE WAREHOUSE DATA_API_WH WITH WAREHOUSE_SIZE='medium'; 
CREATE ROLE DATA_API_ROLE;
CREATE DATABASE HUMAN_RESOURCES;
CREATE SCHEMA HUMAN_RESOURCES.EMPLOYEE_HIRING_DATA;

CREATE OR REPLACE TABLE HUMAN_RESOURCES.EMPLOYEE_HIRING_DATA.TBL_HIRED_EMPLOYEES(
    ID_H_EP INTEGER,
    NAME_H_EP VARCHAR(500),
    DATETIME_H_EP TIMESTAMP,
    DEPARTMENT_ID INTEGER,
    JOB_ID INTEGER,
    ETL_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP()

);

CREATE OR REPLACE TABLE HUMAN_RESOURCES.EMPLOYEE_HIRING_DATA.TBL_DEPARTMENTS(
    ID_D INTEGER,
    DEPARTMENT_NAME VARCHAR(200),
    ETL_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE HUMAN_RESOURCES.EMPLOYEE_HIRING_DATA.TBL_JOBS(
    ID_J INTEGER,
    JOB_NAME VARCHAR(200),
    ETL_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

GRANT USAGE ON WAREHOUSE DATA_API_WH TO ROLE DATA_API_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE HUMAN_RESOURCES TO ROLE DATA_API_ROLE;

CREATE USER "DATA_API" PASSWORD='<SNOWFLAKE USER PASSWORD>' DEFAULT_ROLE=DATA_API_ROLE DEFAULT_WAREHOUSE=DATA_API_WH DEFAULT_NAMESPACE=SNOWFLAKE_SAMPLE_DATA.TPCH_SF10 MUST_CHANGE_PASSWORD=FALSE;



GRANT ROLE DATA_API_ROLE TO USER DATA_API;


SELECT *
FROM HUMAN_RESOURCES.EMPLOYEE_HIRING_DATA.TBL_HIRED_EMPLOYEES;

