name: Test coverage for the microservices
on:
  push:
    branches: 
      - develop
jobs:
  test_uploads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install pipenv
        working-directory: ./uploads
        run: pip install pipenv
      - name: Install dependencies
        working-directory: ./uploads
        run: pipenv install --dev
      - name: Run unit tests
        working-directory: ./uploads
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70
  test_analytics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install pipenv
        working-directory: ./analytics
        run: pip install pipenv
      - name: Install dependencies
        working-directory: ./analytics
        run: pipenv install --dev
      - name: Run unit tests
        working-directory: ./analytics
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70
